image: python:3.12.7


stages:
  - build

before_script:
  - pip install virtualenv
  - virtualenv venv
  - source venv/bin/activate
  - source .setup

# artifacts:reports:codequality

.base_ruff:
  stage: build
  interruptible: true
  image:
    name: ghcr.io/astral-sh/ruff:0.8.3-alpine
  before_script:
    - cd $CI_PROJECT_DIR
    - ruff --version

Ruff Check:
  extends: .base_ruff
  script:
    - ruff check --output-format=gitlab > code-quality-report.json
  artifacts:
    reports:
      codequality: $CI_PROJECT_DIR/code-quality-report.json
