#################################
## General parameters
#################################

# Benchmark file name
benchmark: ./ising/MIMO.txt

# Number of iteration to check in each trial (trail length)
iter_list:
  - 50000

# Solver to use: [BRIM, SA, bSB, dSB, SCA, Multiplicative, all]
solvers:
  - Multiplicative

# Number of trials
nb_runs: 50

# Use gurobi or not
use_gurobi: False

# Use multiprocessing or not
use_multiprocessing: False

initialization_seed: 42


#################################
## Output parameters
#################################
# Folder to save the results
fig_folder: no_backup/figs/

# Name of the file to save the results
fig_name: .png

#################################
## Low-level hyperparameters
#################################

# Parameters for MIMO
SNR: 60
Nt: 5
Nr: 5
M: 4

# Parameters for Multiplicative
dtMult: 1e-5
T_cont: 0.0
T_final_cont: 0.0005
resistance: 1
capacitance: 1
nb_flipping: 100
cluster_threshold: 0.3
init_cluster_size: 0.875
end_cluster_size: 0.0625

# Parameters for BRIM
dtBRIM: 1e-6  # 10us
stop_criterion: 1e-6  # 1uV

# Parameters for SA
T: 50.0
T_final: 0.05
seed: 100

# Parameters for SCA
q: 0.0
q_final: 10.0

# Parameters for SB
dtSB: 0.25
a0: 1.0
c0: 0.0