C: 1
M: 4
Nr: 2
Nt: 2
SNR: None
T: 50.0
T_cont: 0.05
T_final: 0.05
T_final_cont: 0.0005
a0: 1.0
benchmark: ising/benchmarks/TSP/tsp225.tsp
c0: 0.0
capacitance: 1
coupling_annealing: false
dtBRIM: 1e-6
dtMult: 0.01
dtSB: 0.15
fig_folder: no_backup/figs/
fig_name: .png
flipping: 1
flipping_freq: 1
flipping_prob: 1
initialization_seed: 42
iter_list:
- 2000
mu_param: 1
nb_runs: 100
noise: 0.05
offset_ratio: 0.0
offset_type: others
q: 0.0
q_final: 10.0
quantization: false
quantization_precision: 0.0
resistance: 1
seed: 100
solvers:
- bSB
stop_criterion: 1e-6
use_gurobi: false
use_multiprocessing: false
weight_constant: 1.0
