#################################
## General parameters
#################################

# Benchmark file name
benchmark: ./ising/benchmarks/G/G2.txt

# Number of iteration to check in each trial (trail length)
iter_list:
  - 50000

# Solver to use: [BRIM, SA, bSB, dSB, SCA, Multiplicative, all]
solvers:
  - dSB

# Number of trials
nb_runs: 10

# Use gurobi or not
use_gurobi: False

# Use multiprocessing or not
use_multiprocessing: False

#################################
## Output parameters
#################################
# Folder to save the results
fig_folder: no_backup/figs/

# Name of the file to save the results
fig_name: .png

#################################
## Low-level hyperparameters
#################################
# Parameters for TSP
weight_constant: 1.0

# Parameters for MIMO
SNR: None
Nt: 2
Nr: 2
M: 4

# Parameters for Multiplicative
dtMult: 0.01
T_cont: 0.05
T_final_cont: 0.0005
coupling_annealing: False
resistance: 1
flipping: 1
flipping_freq: 1
flipping_prob: 1
mu_param: 1
capacitance: 1

# Parameters for BRIM
dtBRIM: 1e-6  # 10us
C: 1
stop_criterion: 1e-6  # 1uV
noise: 0.05

# Parameters for SA
T: 50.0
T_final: 0.05
seed: 100

# Parameters for SCA
q: 0.0
q_final: 10.0

# Parameters for SB
dtSB: 0.01
a0: 1.0
c0: 0.0