#################################
## General parameters
#################################

# Benchmark file name
benchmark: ./ising/benchmarks/G/G2.txt

# Number of iteration to check in each trial (trail length)
iter_list:
  - 50000

# Solver to use: [BRIM, SA, bSB, dSB, SCA, Multiplicative, all]
solvers:
  - dSB

# Number of trials
nb_runs: 10

# Use gurobi or not
use_gurobi: False

# Use multiprocessing or not
use_multiprocessing: False

#################################
## Solvers hyperparameters
#################################

# Parameters for SA
T: 50.0
T_final: 0.05
seed: 100

# Parameters for SCA
q: 0.0
q_final: 10.0

# Parameters for Multiplicative
dtMult: 0.01
T_cont: 0.05
T_final_cont: 0.0005
resistance: 1
flipping: 1
flipping_freq: 1
flipping_prob: 1
mu_param: -3.55
capacitance: 1

# Parameters for BRIM
dtBRIM: 1e-6  # 10us
stop_criterion: 1e-6  # 1uV

# Parameters for SB
dtSB: 0.01
a0: 1.0
c0: 0.0

#################################
## Problems hyperparameters
#################################

# Parameters for TSP
weight_constant: 0

# Parameters for MIMO
SNR: None
Nt: 2
Nr: 2
M: 4

#################################
## Specific Stages hyperparameters
#################################

# Parameters for quantization stage
quantization: False
quantization_precision: 1.5

# Parameters for npmos stage
offset_type: others
offset_ratio: 0.3

# Parameters for noise stage
device_noise: False
noise_level: 0.1
