#################################
## General parameters
#################################

# Benchmark file name
benchmark: ./ising/MIMO.txt

# Number of iteration to check in each trial (trail length)
iter_list:
  - 50000

# Solver to use: [BRIM, SA, bSB, dSB, SCA, Multiplicative, all]
solvers:
  - Multiplicative

# Number of trials
nb_runs: 50

# Use gurobi or not
use_gurobi: False

# Use multiprocessing or not
use_multiprocessing: False

initialization_seed: 42


#################################
## Solvers hyperparameters
#################################
# Folder to save the results
fig_folder: no_backup/figs/

# Name of the file to save the results
fig_name: .png

#################################
## Low-level hyperparameters
#################################
# Parameters for TSP
weight_constant: 1.0

# Parameters for MIMO
SNR: None
Nt: 2
Nr: 2
M: 4

# Parameters for Multiplicative
dtMult: 0.01
T_cont: 0.05
T_final_cont: 0.0005
resistance: 1
flipping: 1
flipping_freq: 1
flipping_prob: 1
mu_param: -3.55
capacitance: 1

# Parameters for BRIM
dtBRIM: 1e-6  # 10us
stop_criterion: 1e-6  # 1uV

# Parameters for MIMO
SNR: 60
Nt: 5
Nr: 5
M: 4

# Parameters for Multiplicative
dtMult: 1e-5
T_cont: 0.0
T_final_cont: 0.0005
resistance: 1
capacitance: 1
nb_flipping: 100
cluster_threshold: 0.3
init_cluster_size: 0.875
end_cluster_size: 0.0625

# Parameters for BRIM
dtBRIM: 1e-6  # 10us
stop_criterion: 1e-6  # 1uV

# Parameters for SB
dtSB: 0.25
a0: 1.0
c0: 0.0

#################################
## Problems hyperparameters
#################################

# Parameters for TSP
weight_constant: 0

# Parameters for MIMO
SNR: None
Nt: 2
Nr: 2
M: 4

#################################
## Specific Stages hyperparameters
#################################

# Parameters for quantization stage
quantization: False
quantization_precision: 1.5

# Parameters for npmos stage
offset_type: others
offset_ratio: 0.3

# Parameters for noise stage
device_noise: False
noise_level: 0.1
